import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import fs from "node:fs"; import os from "node:os"; import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nt-smoke-"));
const P = "NT"; let fail = 0; const out = [];
const txt = r => (r.content && r.content[0] && r.content[0].text) || "";
const t = new StdioClientTransport({ command: process.execPath, args: [path.join("server","index.js")], cwd: root, env: { ...process.env, FEATUREBOARD_DATA_DIR: dir } });
const c = new Client({ name: "nt", version: "1.0.0" }, { capabilities: {} });
await c.connect(t);
const call = (n, a={}) => c.callTool({ name: n, arguments: { project: P, ...a } });
async function ok(n, a, label) { try { const r = await (n==="__usage"?c.callTool({name:"set_usage_type",arguments:{type:"personal"}}):call(n,a)); if(r.isError) throw new Error(txt(r)); out.push("ok "+(label||n)); } catch(e){ out.push("FAIL "+(label||n)+": "+e.message); fail++; } }
await ok("__usage");
await c.callTool({ name:"create_project", arguments:{ name:P } });
await ok("set_site", { title:"NT", sections:[{heading:"H",body:"B"}] });
await ok("add_page", { slug:"about", title:"About", sections:[{heading:"A",body:"b"}] });
await ok("list_pages", {});
await ok("upload_site_asset", { name:"logo.png", content:Buffer.from("PNG").toString("base64") });
await ok("set_site_analytics", { provider:"plausible", id:"ex.com" });
await ok("save_media", { name:"promo.html", content:"<h1>Promo</h1>", title:"Promo" });
await ok("publish_media_to_site", { name:"promo.html", slug:"promo-post" });
await ok("save_test_page", { name:"qa", html:"<h1>QA</h1>" });
await ok("list_test_pages", {});
await ok("deploy_site", {}, "deploy_site (git off → returns skipped)");
await c.close();
console.log(out.map(l=>"  "+(l.startsWith("ok")?"✓ "+l.slice(3):"✗ "+l.slice(5))).join("\n"));
console.log(`  ${out.length-fail}/${out.length} new-tool calls ok`);
fs.rmSync(dir,{recursive:true,force:true});
process.exit(fail?1:0);
