#!/usr/bin/env node
/**
 * gen-docs.mjs (FBMCPF-52) — generate docs/TOOLS.md from the tools registered in
 * server/index.js. Source of truth is the code: we parse each server.registerTool
 * call for its name, title, description and read-only/destructive annotations, then
 * emit a grouped one-pager. Run: `npm run docs`.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = fs.readFileSync(path.join(root, "server", "index.js"), "utf8");

// Split into per-tool chunks on registerTool( boundaries.
const chunks = src.split(/server\.registerTool\(/).slice(1);
const tools = [];
for (const c of chunks) {
  const name = (c.match(/^\s*"([^"]+)"/) || [])[1];
  if (!name) continue;
  const title = (c.match(/title:\s*"((?:[^"\\]|\\.)*)"/) || [])[1] || name;
  // description may be several concatenated string literals up to the next key
  const descBlock = (c.match(/description:\s*([\s\S]*?)(?:inputSchema:|annotations:|\n\s*},)/) || [])[1] || "";
  const desc = (descBlock.match(/"((?:[^"\\]|\\.)*)"/g) || [])
    .map((s) => s.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, "\\"))
    .join("");
  const readOnly = /readOnlyHint:\s*true/.test(c);
  const destructive = /destructiveHint:\s*true/.test(c);
  tools.push({ name, title, desc, readOnly, destructive });
}

const badge = (t) => (t.readOnly ? "🟢 read-only" : t.destructive ? "🔴 destructive" : "🟡 write");
const lines = [];
lines.push("# FeatureBoard MCP — Tool reference");
lines.push("");
lines.push(`_Auto-generated by \`npm run docs\` from \`server/index.js\`. ${tools.length} tools._`);
lines.push("");
lines.push("| Tool | Access | Description |");
lines.push("| --- | --- | --- |");
for (const t of tools) {
  lines.push(`| \`${t.name}\` | ${badge(t)} | ${t.desc.replace(/\|/g, "\\|")} |`);
}
lines.push("");

const outDir = path.join(root, "docs");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "TOOLS.md"), lines.join("\n"), "utf8");
console.log(`Wrote docs/TOOLS.md (${tools.length} tools).`);

// Keep manifest.json's tools array (the directory annotation surface) in sync.
const manifestPath = path.join(root, "manifest.json");
try {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  manifest.tools = tools.map((t) => ({ name: t.name, description: t.desc }));
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  console.log(`Synced manifest.json tools (${manifest.tools.length}).`);
} catch (e) {
  console.warn("Skipped manifest sync:", e.message);
}
